# Generated by Django 5.2.3 on 2025-07-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_transaction_payer_str_transaction_receiver_str'),
        ('storage', '0011_alter_sonyaccount_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='storage.product'),
        ),
    ]
