# Generated by Django 5.2.3 on 2025-07-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
