# Generated by Django 5.2.3 on 2025-07-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
