# Generated by Django 5.2.3 on 2025-07-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_postal_code'),
        ('payments', '0020_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('customer', 'سفارش از طریق مشتری'), ('employee', 'سفارش از طریق کارمند')], default='customer', max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customers.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
