# Generated by Django 5.2.3 on 2025-07-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='order_type',
            field=models.CharField(choices=[('customer', 'سفارش از طریق مشتری'), ('employee', 'سفارش از طریق کارمند')], default='customer', max_length=30),
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='selected_games_count',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='product',
        ),
        migrations.AddField(
            model_name='gameorder',
            name='console',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='console',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='delivery_to_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_customer', to='payments.deliveryman'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='delivery_to_drgame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_drgame', to='payments.deliveryman'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='delivery_to_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_to_customer', to='payments.deliveryman'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='delivery_to_drgame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_to_drgame', to='payments.deliveryman'),
        ),
        migrations.DeleteModel(
            name='GameOrderType',
        ),
    ]
