# Generated by Django 5.2.3 on 2025-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_gameorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پذداخت نشده')], default='unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار پرداخت'), ('paid_and_waiting_for_delivery', 'پرداخت شده و در انتظار پیک'), ('delivered_to_drgame', 'تحویل شده به دکتر گیم'), ('account_setting_queue', 'در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('data_uploading_in_progress', 'در حال ریخته شدن داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده توسط مشتری')], default='waiting', max_length=50),
        ),
    ]
