# Generated by Django 5.2.3 on 2025-07-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_paymentmethod_alter_gameorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='in_out',
            field=models.BooleanField(default=True),
        ),
    ]
