# Generated by Django 5.2.3 on 2025-08-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_transaction_in_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='course_order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='game_order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='repair_order',
        ),
        migrations.AddField(
            model_name='courseorder',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_order', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_order', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair', to='payments.transaction'),
        ),
    ]
