# Generated by Django 5.2.3 on 2025-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_remove_transaction_course_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=30),
        ),
    ]
