# Generated by Django 5.2.3 on 2025-08-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_has_access_to_products_employee_has_access_to_site'),
        ('payments', '0033_order_payment_status'),
        ('storage', '0018_remove_game_price_game_data_ps4_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameorder',
            name='games',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='games_count',
        ),
        migrations.AddField(
            model_name='gameorder',
            name='order_console_type',
            field=models.CharField(choices=[('online_ps4', 'online_ps4'), ('online_ps5', 'online_ps5'), ('offline_ps4', 'offline_ps4'), ('offline_ps5', 'offline_ps5'), ('data_ps4', 'data_ps4'), ('data_ps5', 'data_ps5'), ('xbox', 'xbox'), ('nintendo', 'nintendo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('paid_and_waiting_for_delivery', 'پرداخت شده و در انتظار پیک'), ('delivered_to_drgame', 'تحویل شده به دکتر گیم'), ('account_setting_queue', 'در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('data_uploading_in_progress', 'در حال ریخته شدن داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='waiting', max_length=50),
        ),
        migrations.CreateModel(
            name='GameOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.game')),
                ('game_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.gameorder')),
            ],
        ),
    ]
