# Generated by Django 5.2.3 on 2025-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_remove_gameorder_games_remove_gameorder_games_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('waiting_for_delivery', 'پرداخت شده و در انتظار پیک'), ('delivered_to_drgame', 'تحویل شده به دکتر گیم'), ('account_setting_queue', 'در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('data_uploading_in_progress', 'در حال ریخته شدن داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='waiting', max_length=50),
        ),
    ]
