# Generated by Django 5.2.3 on 2025-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_alter_gameorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameorderitem',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
