# Generated by Django 5.2.3 on 2025-08-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_alter_gameorder_amount_alter_gameorderitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorderitem',
            name='game_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='payments.gameorder'),
        ),
    ]
