# Generated by Django 5.2.3 on 2025-08-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_alter_gameorderitem_game_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='dead_line',
            field=models.DateField(blank=True, null=True),
        ),
    ]
