# Generated by Django 5.2.3 on 2025-08-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_has_access_to_products_employee_has_access_to_site'),
        ('payments', '0038_gameorder_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='employees.employee'),
        ),
    ]
