# Generated by Django 5.2.3 on 2025-08-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_has_access_to_course'),
        ('employees', '0012_rename_has_access_to_products_employee_has_access_to_site'),
        ('payments', '0039_gameorder_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameorder',
            name='account_setter',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='data_uploader',
        ),
        migrations.RemoveField(
            model_name='gameorderitem',
            name='employee',
        ),
        migrations.AddField(
            model_name='gameorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employee', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='account_setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_setter', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='data_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_uploader', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='employees.employee'),
        ),
    ]
