# Generated by Django 5.2.3 on 2025-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_remove_gameorder_account_setter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameorderitem',
            old_name='is_done',
            new_name='account',
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='data',
            field=models.BooleanField(default=False),
        ),
    ]
