# Generated by Django 5.2.3 on 2025-08-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_rename_is_done_gameorderitem_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('waiting_for_delivery', 'پرداخت شده و در انتظار تحویل به دکتر گیم'), ('delivered_to_drgame_and_in_waiting_queue', 'تحویل شده به دکتر گیم و در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('in_data_uploading_queue', 'در انتظار اپلود داده'), ('data_uploading_in_progress', 'در حال اپلود داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='waiting', max_length=50),
        ),
    ]
