# Generated by Django 5.2.3 on 2025-08-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_repairorder_repair_man_repairorder_repairman_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_order', to='payments.transaction'),
        ),
    ]
