# Generated by Django 5.2.3 on 2025-08-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_alter_gameorder_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='delivery_to_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_customer', to='payments.deliveryman'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='delivery_to_drgame',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_drgame', to='payments.deliveryman'),
        ),
    ]
