# Generated by Django 5.2.3 on 2025-08-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0045_alter_gameorder_delivery_to_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='payment_status',
            field=models.CharField(choices=[('پرداخت شده', 'paid'), ('پرداخت نشده', 'unpaid')], default='unpaid', max_length=30),
        ),
    ]
