# Generated by Django 5.2.3 on 2025-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_repairorder_dead_line_alter_repairorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
