# Generated by Django 5.2.3 on 2025-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0048_alter_gameorder_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
