# Generated by Django 5.2.3 on 2025-08-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_repairman_balance'),
        ('payments', '0049_alter_paymentmethod_balance'),
        ('storage', '0022_realassetscategory_realassets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('sony_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.sonyaccount')),
            ],
        ),
    ]
