# Generated by Django 5.2.3 on 2025-12-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0052_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='delivery_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_customer', to='payments.deliveryman'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='delivery_to_drgame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_drgame', to='payments.deliveryman'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('waiting_for_delivery', 'در انتظار تحویل به دکتر گیم'), ('delivered_to_drgame_and_in_waiting_queue', 'تحویل شده به دکتر گیم و در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('in_data_uploading_queue', 'در انتظار اپلود داده'), ('data_uploading_in_progress', 'در حال اپلود داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='delivered_to_drgame_and_in_waiting_queue', max_length=50),
        ),
    ]
