# Generated by Django 5.2.3 on 2026-01-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0054_transactioncategory_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
