# Generated by Django 5.2.3 on 2026-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0055_remove_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramorder',
            name='customer_tel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
