# Generated by Django 5.2.3 on 2025-07-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
