# Generated by Django 5.2.3 on 2025-07-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_doccategory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=200000),
        ),
    ]
