# Generated by Django 5.2.3 on 2025-07-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_deliveryman_alter_gameorder_order_type_and_more'),
        ('storage', '0016_game_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerConsole',
        ),
    ]
