# Generated by Django 5.2.3 on 2025-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_delete_customerconsole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.AddField(
            model_name='game',
            name='data_ps4_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='data_ps5_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='nintendo_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='offline_ps4_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='offline_ps5_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='online_ps4_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='online_ps5_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='xbox_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
