# Generated by Django 5.2.3 on 2025-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_remove_game_price_game_data_ps4_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data_ps4_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='data_ps5_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='nintendo_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='offline_ps4_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='offline_ps5_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_ps4_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_ps5_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='xbox_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
    ]
