# Generated by Django 5.2.3 on 2025-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_game_data_ps4_price_alter_game_data_ps5_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccount',
            name='two_step_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='two_step_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
