# Generated by Django 5.2.3 on 2025-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_realassetscategory_realassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccountstatus',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
