# Generated by Django 5.2.3 on 2025-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_sonyaccountstatus_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccount',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
