# Generated by Django 5.2.3 on 2026-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_realassets_price_docsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
