# Generated by Django 5.2.3 on 2026-01-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_alter_employee_commission_amount_and_more'),
        ('storage', '0026_game_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='realassets',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_assets', to='employees.employee'),
        ),
    ]
