# Generated by Django 5.2.3 on 2025-07-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_has_access_to_game_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_access_to_add_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_access_to_employees',
            field=models.BooleanField(default=False),
        ),
    ]
