# Generated by Django 5.2.3 on 2025-07-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_has_access_to_add_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='has_access_to_products',
            new_name='has_access_to_site',
        ),
    ]
