# Generated by Django 5.2.3 on 2025-08-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_repairman_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_account_setter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_data_uploader',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('recipient', 'صندوق دار'), ('account_setter', 'اکانت ستر'), ('data_uploader', 'دیتا آپلودر')], max_length=14, null=True),
        ),
    ]
