# Generated by Django 5.2.3 on 2025-08-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_employee_is_account_setter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='employee_files/tasks/voices'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='type',
            field=models.CharField(blank=True, choices=[('Personal', 'شخصی'), ('Organize', 'سازمانی')], default='Personal', max_length=20, null=True),
        ),
    ]
