# Generated by Django 5.2.3 on 2025-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employeetask_voice_alter_employeetask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('recipient', 'صندوق دار'), ('account_setter', 'اکانت ستر'), ('data_uploader', 'دیتا آپلودر'), ('manager', 'مدیر داخلی')], max_length=14, null=True),
        ),
    ]
