# Generated by Django 5.2.3 on 2025-08-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employee'),
        ),
    ]
