# Generated by Django 5.2.3 on 2025-08-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employeefile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('leave', 'مرخصی'), ('favorable', 'مساعده'), ('miscellaneous', 'متفرقه')], max_length=20)),
                ('description', models.TextField(max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
