# Generated by Django 5.2.3 on 2025-08-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employeerequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeRequests',
            new_name='EmployeeRequest',
        ),
    ]
