# Generated by Django 5.2.3 on 2025-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_rename_employeerequests_employeerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
