# Generated by Django 5.2.3 on 2025-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_rename_has_access_to_accounts_employee_has_access_to_add_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_access_to_requests',
            field=models.BooleanField(default=False),
        ),
    ]
