# Generated by Django 5.2.3 on 2025-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_employee_has_access_to_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
