# Generated by Django 5.2.3 on 2025-08-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_employeehire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehire',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='hire/resume_files/'),
        ),
    ]
