# Generated by Django 5.2.3 on 2025-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_alter_employeehire_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('planed', 'برنامه ریزی شده'), ('inـprogress', 'در حال انجام'), ('done', 'انجام شده')], max_length=20),
        ),
    ]
