# Generated by Django 5.2.3 on 2025-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_alter_employeetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('planed', 'برنامه ریزی شده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], max_length=20),
        ),
    ]
