# Generated by Django 5.2.3 on 2025-12-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_alter_employeetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_commission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
