# Generated by Django 5.2.3 on 2026-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_alter_employee_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='waiting', max_length=20),
        ),
    ]
