# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('orders', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonyAccountBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('two_step', models.IntegerField(blank=True, null=True)),
                ('bank_account_status', models.BooleanField(blank=True, null=True)),
                ('plus', models.BooleanField(blank=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('America', 'america'), ('Europe', 'europe'), ('Asia', 'asia'), ('Mix', 'mix')], max_length=100, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('two_step_secret', models.TextField(blank=True, null=True)),
                ('two_step_enabled', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_accounts', to='hr.employee')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psn.sonyaccountbank')),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_capability_after', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_actions', to='hr.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='orders.sonyaccountorder')),
                ('sony_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_actions', to='psn.sonyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to='website.game')),
                ('sony_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_games', to='psn.sonyaccount')),
            ],
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='games',
            field=models.ManyToManyField(related_name='users', through='psn.SonyAccountGame', to='website.game'),
        ),
        migrations.CreateModel(
            name='SonyAccountSellMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.sonyaccountordercategory')),
            ],
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='sell_method',
            field=models.ManyToManyField(to='psn.sonyaccountsellmethod'),
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psn.sonyaccountstatus'),
        ),
        migrations.AddIndex(
            model_name='sonyaccountgame',
            index=models.Index(fields=['sony_account', 'game'], name='psn_sonyacc_sony_ac_f46173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sonyaccountgame',
            unique_together={('sony_account', 'game')},
        ),
    ]
