# Generated by Django 5.2.3 on 2026-07-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employeerequesttype_remove_repairman_user_and_more'),
        ('orders', '0003_productorderactionlog_item_id_and_more'),
        ('psn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonyAccountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_capability_after', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_actions', to='hr.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='orders.sonyaccountorder')),
                ('sony_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_actions', to='psn.sonyaccount')),
            ],
        ),
    ]
