# Generated by Django 5.2.3 on 2026-07-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sonyaccountordercategory_base_price'),
        ('psn', '0002_sonyaccountaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonyaccount',
            name='is_owned',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SonyAccountSellMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.sonyaccountordercategory')),
            ],
        ),
        migrations.AddField(
            model_name='sonyaccount',
            name='sell_method',
            field=models.ManyToManyField(to='psn.sonyaccountsellmethod'),
        ),
    ]
