# Generated by Django 5.2.3 on 2026-06-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0003_employeerole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='employee_files/tasks/voices')),
                ('type', models.CharField(choices=[('Personal', 'شخصی'), ('Organize', 'سازمانی')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='employee_files/tasks/voices')),
                ('type', models.CharField(blank=True, choices=[('Personal', 'شخصی'), ('Organize', 'سازمانی')], default='Personal', max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('planed', 'برنامه ریزی شده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], max_length=20)),
                ('priority', models.CharField(choices=[('immediate', 'فوری'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین'), ('very_low', 'فاقد اهمیت')], max_length=20)),
                ('has_reward', models.BooleanField(default=False)),
                ('reward_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
