# Generated by Django 5.2.3 on 2026-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeerole_and_more'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='employee',
        ),
        migrations.AlterField(
            model_name='plannedtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='employee',
            field=models.ManyToManyField(to='hr.employee'),
        ),
    ]
