# Generated by Django 5.2.3 on 2026-06-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_remove_dailytask_is_done_remove_dailytask_voice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='employee',
            new_name='employees',
        ),
    ]
