# Generated by Django 5.2.3 on 2026-07-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='main_img/game/')),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('online_ps4_price', models.IntegerField(blank=True, null=True)),
                ('online_ps5_price', models.IntegerField(blank=True, null=True)),
                ('offline_ps4_price', models.IntegerField(blank=True, null=True)),
                ('offline_ps5_price', models.IntegerField(blank=True, null=True)),
                ('data_ps4_price', models.IntegerField(blank=True, null=True)),
                ('data_ps5_price', models.IntegerField(blank=True, null=True)),
                ('xbox_price', models.IntegerField(blank=True, null=True)),
                ('nintendo_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_trend', models.BooleanField(default=False)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gamecartitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.game'),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/games/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_images', to='website.game')),
            ],
        ),
    ]
