# Generated by Django 5.2.3 on 2026-07-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerwishlist'),
        ('hr', '0004_employeerequesttype_remove_repairman_user_and_more'),
        ('inventory', '0003_remove_docsubcategory_category_and_more'),
        ('website', '0002_game_alter_gamecartitem_game_gameimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Blog Post Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_content', models.CharField(choices=[('game', 'بازی'), ('product', 'کالا'), ('blog', 'بلاگ')], max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.homesection')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='website.storeproduct')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='ProductCart',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='ProductCartItem',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='team_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='data_ps4_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='data_ps5_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_trend',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nintendo_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='offline_ps4_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='offline_ps5_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_ps4_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_ps5_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xbox_price',
        ),
        migrations.RemoveField(
            model_name='gamecart',
            name='type',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.TextField(default='h'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='e_namaad',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='e_namaad_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default='h', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(default='h', upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(default='j', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='h'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogpostcategory'),
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.blogpost'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.gamecategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
