# Generated by Django 5.2.3 on 2026-07-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpostcategory_blogpostimage_gamecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
