# Generated by Django 5.2.3 on 2026-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blogpostimage_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcartitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
