# Generated by Django 5.2.3 on 2026-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/hr/')),
                ('role', models.CharField(blank=True, choices=[('recipient', 'صندوق دار'), ('account_setter', 'اکانت ستر'), ('data_uploader', 'دیتا آپلودر'), ('manager', 'مدیر داخلی')], max_length=14, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('national_code', models.CharField(max_length=10, null=True)),
                ('employee_id', models.CharField(max_length=11, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('has_commission', models.BooleanField(blank=True, default=False, null=True)),
                ('commission_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('has_access_to_organize_tasks', models.BooleanField(default=False)),
                ('has_access_to_game_orders', models.BooleanField(default=False)),
                ('has_access_to_product_order', models.BooleanField(default=False)),
                ('has_access_to_repair_order', models.BooleanField(default=False)),
                ('has_access_to_personal_account', models.BooleanField(default=False)),
                ('has_access_to_all_accounts', models.BooleanField(default=False)),
                ('has_access_to_add_accounts', models.BooleanField(default=False)),
                ('has_access_to_transactions', models.BooleanField(default=False)),
                ('has_access_to_customer_read', models.BooleanField(default=False)),
                ('has_access_to_customer_write', models.BooleanField(default=False)),
                ('has_access_to_employees_read', models.BooleanField(default=False)),
                ('has_access_to_employees_write', models.BooleanField(default=False)),
                ('has_access_to_repairmen_read', models.BooleanField(default=False)),
                ('has_access_to_repairmen_write', models.BooleanField(default=False)),
                ('has_access_to_docs_read', models.BooleanField(default=False)),
                ('has_access_to_docs_write', models.BooleanField(default=False)),
                ('has_access_to_assets_read', models.BooleanField(default=False)),
                ('has_access_to_assets_write', models.BooleanField(default=False)),
                ('has_access_to_products', models.BooleanField(default=False)),
                ('has_access_to_game_store', models.BooleanField(default=False)),
                ('has_access_to_blogs', models.BooleanField(default=False)),
                ('has_access_to_messenger', models.BooleanField(default=False)),
                ('has_access_to_reports', models.BooleanField(default=False)),
                ('has_access_to_requests', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='hire/resume_files/')),
                ('phone_number', models.CharField(max_length=11)),
                ('description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('leave', 'مرخصی'), ('favorable', 'مساعده'), ('miscellaneous', 'متفرقه')], max_length=20)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('waiting', 'در انتظار بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='waiting', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='employee_files/tasks/voices')),
                ('type', models.CharField(blank=True, choices=[('Personal', 'شخصی'), ('Organize', 'سازمانی')], default='Personal', max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('planed', 'برنامه ریزی شده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/repairmen/')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('national_code', models.CharField(max_length=10, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
