# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeearrival',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeovertime',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeovertime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtimes', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employeerequesttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='hr.employeerole'),
        ),
        migrations.AddField(
            model_name='employmentresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action', 'extra_flag')},
        ),
        migrations.AddField(
            model_name='employeerole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='hr.permission'),
        ),
    ]
