# Generated by Django 5.2.3 on 2026-06-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('access_to_dashboard', models.BooleanField(default=False)),
                ('can_read_task_manager', models.BooleanField(default=False)),
                ('can_write_task_manager', models.BooleanField(default=False)),
                ('can_read_accounting', models.BooleanField(default=False)),
                ('can_write_accounting', models.BooleanField(default=False)),
                ('can_read_inventory', models.BooleanField(default=False)),
                ('can_write_inventory', models.BooleanField(default=False)),
                ('access_to_all_inventory', models.BooleanField(default=False)),
                ('can_read_orders', models.BooleanField(default=False)),
                ('can_write_orders', models.BooleanField(default=False)),
                ('can_read_account_orders', models.BooleanField(default=False)),
                ('can_write_account_orders', models.BooleanField(default=False)),
                ('access_to_all_accounts', models.BooleanField(default=False)),
                ('is_account_employee', models.BooleanField(default=False)),
                ('can_read_repairs', models.BooleanField(default=False)),
                ('can_write_repairs', models.BooleanField(default=False)),
                ('can_read_hr', models.BooleanField(default=False)),
                ('can_write_hr', models.BooleanField(default=False)),
                ('can_read_site', models.BooleanField(default=False)),
                ('can_write_site', models.BooleanField(default=False)),
                ('can_read_branch', models.BooleanField(default=False)),
                ('can_write_branch', models.BooleanField(default=False)),
                ('can_read_docs', models.BooleanField(default=False)),
                ('can_write_docs', models.BooleanField(default=False)),
                ('can_change_setting', models.BooleanField(default=False)),
                ('access_to_messenger', models.BooleanField(default=False)),
                ('can_start_chat', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_add_accounts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_all_accounts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_assets_read',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_assets_write',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_blogs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_customer_read',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_customer_write',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_docs_read',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_docs_write',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_employees_read',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_employees_write',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_game_orders',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_game_store',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_messenger',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_organize_tasks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_personal_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_product_order',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_products',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_repair_order',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_repairmen_read',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_repairmen_write',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_reports',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_requests',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_access_to_transactions',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employeerole'),
        ),
        migrations.DeleteModel(
            name='EmployeeTask',
        ),
    ]
