# Generated by Django 5.2.3 on 2025-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmanager',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
