# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realassets',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_assets', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='realassetssubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cats', to='docs.realassetscategory'),
        ),
        migrations.AddField(
            model_name='realassets',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_assets', to='docs.realassetssubcategory'),
        ),
    ]
