# Generated by Django 5.2.3 on 2026-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, help_text='شماره حساب', max_length=50, null=True)),
                ('sheba', models.CharField(blank=True, help_text='شماره شبا', max_length=30, null=True)),
                ('national_id', models.CharField(blank=True, help_text='کد ملی (حقیقی) یا شناسه ملی (حقوقی)', max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='شناسه مالیاتی', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
