# Generated by Django 5.2.3 on 2026-07-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='realassets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='realassets',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='realassetssubcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='DocCategory',
        ),
        migrations.DeleteModel(
            name='DocSubCategory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductCompany',
        ),
        migrations.DeleteModel(
            name='RealAssets',
        ),
        migrations.DeleteModel(
            name='RealAssetsCategory',
        ),
        migrations.DeleteModel(
            name='RealAssetsSubCategory',
        ),
    ]
