# Generated by Django 5.2.3 on 2026-07-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='games',
        ),
        migrations.RemoveField(
            model_name='sonyaccountgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='realassets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='realassets',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='realassetssubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sonyaccountgame',
            name='sony_account',
        ),
        migrations.AlterUniqueTogether(
            name='sonyaccountgame',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='حداقل موجودی'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='products', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='ProductEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='main_img/products/entities/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'ورودی'), ('out', 'خروجی'), ('rejected', 'برگشتی')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('product_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.productentity')),
            ],
        ),
        migrations.DeleteModel(
            name='DocCategory',
        ),
        migrations.DeleteModel(
            name='DocSubCategory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductCompany',
        ),
        migrations.DeleteModel(
            name='RealAssets',
        ),
        migrations.DeleteModel(
            name='RealAssetsCategory',
        ),
        migrations.DeleteModel(
            name='RealAssetsSubCategory',
        ),
        migrations.DeleteModel(
            name='SonyAccountBank',
        ),
        migrations.DeleteModel(
            name='SonyAccountStatus',
        ),
        migrations.DeleteModel(
            name='SonyAccount',
        ),
        migrations.DeleteModel(
            name='SonyAccountGame',
        ),
    ]
