# Generated by Django 5.2.3 on 2026-07-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_docsubcategory_category_and_more'),
        ('website', '0002_game_alter_gamecartitem_game_gameimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonyaccountgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='games',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sonyaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sonyaccountgame',
            name='sony_account',
        ),
        migrations.AlterUniqueTogether(
            name='sonyaccountgame',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(null=True, related_name='products', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='ProductEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='main_img/products/entities/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'ورودی'), ('out', 'خروجی')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('product_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.productentity')),
            ],
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='SonyAccountBank',
        ),
        migrations.DeleteModel(
            name='SonyAccountStatus',
        ),
    ]
