# Generated by Django 5.2.3 on 2026-07-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_sonyaccountgame_game_remove_sonyaccount_games_and_more'),
        ('orders', '0002_alter_sonyaccountorderitem_sony_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SonyAccount',
        ),
        migrations.DeleteModel(
            name='SonyAccountGame',
        ),
    ]
