# Generated by Django 5.2.3 on 2026-07-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_sonyaccount_delete_sonyaccountgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='products', to='inventory.supplier'),
        ),
    ]
