# Generated by Django 5.2.3 on 2026-07-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_supplier_email_remove_supplier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='حداقل موجودی'),
        ),
    ]
