# Generated by Django 5.2.3 on 2025-07-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_blogpost_category_remove_blogpost_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
