# Generated by Django 5.2.3 on 2025-07-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_discount_customer_is_business_and_more'),
        ('home', '0031_alter_cart_user'),
        ('storage', '0016_game_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(blank=True, to='storage.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
