# Generated by Django 5.2.3 on 2025-08-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_gamecart'),
        ('storage', '0018_remove_game_price_game_data_ps4_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecart',
            name='games',
        ),
        migrations.AddField(
            model_name='gamecart',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamecart',
            name='type',
            field=models.CharField(choices=[('online_ps4', 'online_ps4'), ('online_ps5', 'online_ps5'), ('offline_ps4', 'offline_ps4'), ('offline_ps5', 'offline_ps5'), ('data_ps4', 'data_ps4'), ('data_ps5', 'data_ps5'), ('xbox', 'xbox'), ('nintendo', 'nintendo')], default='online_ps4', max_length=500),
        ),
        migrations.CreateModel(
            name='GameCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.game')),
                ('game_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gamecart')),
            ],
            options={
                'unique_together': {('game', 'game_cart')},
            },
        ),
    ]
