# Generated by Django 5.2.3 on 2025-08-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_gamecart_games_gamecart_price_gamecart_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecartitem',
            name='game_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='home.gamecart'),
        ),
    ]
