# Generated by Django 5.2.3 on 2025-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BusinessCustomer',
        ),
    ]
