# Generated by Django 5.2.3 on 2025-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_access_to_course',
            field=models.BooleanField(default=False),
        ),
    ]
