# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customerwishlist',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customerwishlist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='crm.customer'),
        ),
        migrations.AddIndex(
            model_name='customerwishlist',
            index=models.Index(fields=['customer', 'content_type'], name='crm_custome_custome_4ec67c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerwishlist',
            unique_together={('customer', 'content_type', 'object_id')},
        ),
    ]
