# Generated by Django 5.2.3 on 2026-07-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0003_remove_customer_balance_remove_customer_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='crm.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'content_type'], name='crm_custome_custome_4ec67c_idx')],
                'unique_together': {('customer', 'content_type', 'object_id')},
            },
        ),
    ]
