# Generated by Django 5.2.3 on 2025-08-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
    ]
