# Generated by Django 5.2.3 on 2026-07-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_bankaccount_invoicecategory_and_more'),
        ('crm', '0002_initial'),
        ('hr', '0003_employeerole_and_more'),
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('rent', 'اجاره')], max_length=10)),
                ('rent_time_days', models.IntegerField(blank=True, default=1, null=True)),
                ('account_capacity', models.CharField(choices=[('1', 'Offline'), ('2', 'Online + Offline'), ('3', 'Online')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='crm.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='فاکتور خروجی مرتبط با این سفارش', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='accounting.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='موقت — بعد از آماده شدن مدل Product حذف می\u200cشه', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.productorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('is_in_waiting', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employeerole')),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='orders.productorderstage'),
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_fee', models.IntegerField(blank=True, help_text='هزینه تعمیر', null=True)),
                ('final_amount', models.IntegerField(blank=True, help_text='مبلغ نهایی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_orders', to='crm.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='فاکتور خروجی مرتبط با این سفارش تعمیر', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_orders', to='accounting.invoice')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_orders', to='orders.repairordercategory')),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrderDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_devices', to='crm.customer')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='orders.repairorder')),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('is_in_waiting', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employeerole')),
            ],
        ),
        migrations.AddField(
            model_name='repairorder',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_orders', to='orders.repairorderstage'),
        ),
        migrations.CreateModel(
            name='SonyAccountOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('telegram', 'تلگرام'), ('website', 'سایت'), ('in_person', 'حضوری')], max_length=20)),
                ('type', models.CharField(choices=[('by_customer', 'توسط مشتری'), ('by_employee', 'توسط کارمند')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sony_account_orders', to='crm.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='فاکتور خروجی مرتبط با این سفارش', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sony_account_orders', to='accounting.invoice')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sony_account_orders', to='orders.sonyaccountordercategory')),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountOrderConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sony_consoles', to='crm.customer')),
                ('sony_account_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to='orders.sonyaccountorder')),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sony_order_items', to='hr.employee')),
                ('sony_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.sonyaccount')),
                ('sony_account_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.sonyaccountorder')),
            ],
        ),
        migrations.CreateModel(
            name='SonyAccountOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('is_in_waiting', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employeerole')),
            ],
        ),
        migrations.AddField(
            model_name='sonyaccountorder',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sony_account_orders', to='orders.sonyaccountorderstage'),
        ),
    ]
