# Generated by Django 5.2.3 on 2026-07-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('psn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonyaccountorderitem',
            name='sony_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='psn.sonyaccount'),
        ),
    ]
