# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('orders', '0001_initial'),
        ('psn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccountorderitem',
            name='sony_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='psn.sonyaccount'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderitem',
            name='sony_account_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.sonyaccountorder'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.sonyaccountordercategory'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstage',
            name='employee_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employeerole'),
        ),
        migrations.AddField(
            model_name='sonyaccountorder',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sony_account_orders', to='orders.sonyaccountorderstage'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstageaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='orders.sonyaccountorderstage'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderactionlog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sonyaccountorderstageaction'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstagelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstagelog',
            name='from_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.sonyaccountorderstage'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstagelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='orders.sonyaccountorder'),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstagelog',
            name='to_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.sonyaccountorderstage'),
        ),
        migrations.AlterUniqueTogether(
            name='productorderstage',
            unique_together={('category', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='repairorderstage',
            unique_together={('category', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='sonyaccountorderstage',
            unique_together={('category', 'order')},
        ),
    ]
