# Generated by Django 5.2.3 on 2026-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderstageaction',
            name='target_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='repairorderstageaction',
            name='target_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sonyaccountorderstageaction',
            name='target_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productorderstageaction',
            name='action_type',
            field=models.CharField(choices=[('update_order_field', 'آپدیت فیلد سفارش'), ('update_order_item_field', 'آپدیت فیلد آیتم سفارش'), ('manual_confirm', 'تایید دستی'), ('add_note', 'افزودن یادداشت')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repairorderstageaction',
            name='action_type',
            field=models.CharField(choices=[('update_order_field', 'آپدیت فیلد سفارش'), ('update_order_item_field', 'آپدیت فیلد آیتم سفارش'), ('manual_confirm', 'تایید دستی'), ('add_note', 'افزودن یادداشت')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sonyaccountorderstageaction',
            name='action_type',
            field=models.CharField(choices=[('update_order_field', 'آپدیت فیلد سفارش'), ('update_order_item_field', 'آپدیت فیلد آیتم سفارش'), ('manual_confirm', 'تایید دستی'), ('add_note', 'افزودن یادداشت')], max_length=50),
        ),
    ]
