# Generated by Django 5.2.3 on 2026-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productorderstageaction_target_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderactionlog',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productordercategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairorderactionlog',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sonyaccountorderactionlog',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sonyaccountordercategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
