# Generated by Django 5.2.3 on 2026-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productorderactionlog_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccountordercategory',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
    ]
