# Generated by Django 5.2.3 on 2026-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=2000000, max_digits=10)),
                ('payment_status', models.CharField(choices=[('پرداخت شده', 'paid'), ('پرداخت نشده', 'unpaid')], default='unpaid', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('customer', 'سفارش از طریق مشتری'), ('employee', 'سفارش از طریق کارمند')], default='customer', max_length=30)),
                ('order_console_type', models.CharField(choices=[('online_ps4', 'online_ps4'), ('online_ps5', 'online_ps5'), ('offline_ps4', 'offline_ps4'), ('offline_ps5', 'offline_ps5'), ('data_ps4', 'data_ps4'), ('data_ps5', 'data_ps5'), ('xbox', 'xbox'), ('nintendo', 'nintendo')], max_length=30, null=True)),
                ('console', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting_for_delivery', 'در انتظار تحویل به دکتر گیم'), ('delivered_to_drgame_and_in_waiting_queue', 'تحویل شده به دکتر گیم و در لیست انتظار'), ('account_setting_in_progress', 'در حال ست شدن اکانت'), ('in_data_uploading_queue', 'در انتظار اپلود داده'), ('data_uploading_in_progress', 'در حال اپلود داده'), ('error_on_accounts', 'مشکل در اکانت ها'), ('done', 'انجام شده و در انتظار پیک'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='delivered_to_drgame_and_in_waiting_queue', max_length=50)),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=30)),
                ('dead_line', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('account', models.BooleanField(default=False)),
                ('data', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('customer', 'سفارش از طریق مشتری'), ('employee', 'سفارش از طریق کارمند')], default='customer', max_length=30)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('repairman_fee', models.IntegerField(blank=True, null=True)),
                ('dead_line', models.DateTimeField(blank=True, null=True)),
                ('console', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting_for_delivery_to_drgame', 'در انتظار تحویل به دکترگیم'), ('in_accepting_queue', 'در انتظار قبول شدن توسط تعمیرکار'), ('waiting_for_repairman_fee', 'در انتظار تعیین مبلغ'), ('waiting_for_amount', 'در انتظار تعیین مبلغ توسط دکتر گیم'), ('waiting_for_customer_to_accept', 'در انتظار تایید توسط مشتری'), ('in_progress', 'در حال پردازش'), ('done', 'در انتظار تحویل به مشتری'), ('delivered_to_customer', 'تحویل شده به مشتری')], default='waiting_for_delivery_to_drgame', max_length=50)),
                ('payment_status', models.CharField(choices=[('پرداخت شده', 'paid'), ('پرداخت نشده', 'unpaid')], default='unpaid', max_length=30)),
                ('description', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer_tel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_str', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_str', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('in_out', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
