# Generated by Django 5.2.3 on 2026-08-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sheba', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'ورودی'), ('out', 'خروجی')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('charge_admin', 'شارژ توسط ادمین'), ('charge_gateway', 'شارژ آنلاین'), ('debit_order', 'کسر بابت سفارش'), ('refund', 'برگشت وجه')], max_length=20)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in Toman')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('gateway_ref', models.CharField(blank=True, help_text='Gateway payment ID', max_length=100, null=True)),
                ('gateway_name', models.CharField(blank=True, help_text='Example: zarinpal', max_length=50, null=True)),
                ('order_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('balance_before', models.PositiveBigIntegerField(help_text='Balance before transaction')),
                ('balance_after', models.PositiveBigIntegerField(help_text='Balance after transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('customer', 'مشتری'), ('employee', 'کارمند'), ('supplier', 'تامین\u200cکننده'), ('other', 'سایر')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='Related model type (Customer, Employee, Supplier)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0, help_text='Total paid amount — updated from Celery')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('primary', 'صادر شده'), ('finalize', 'نهایی')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20)),
                ('is_payroll', models.BooleanField(default=False, help_text='Is this invoice a payroll slip?')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.accountside')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.invoicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='Related model type (SonyAccountOrder, RepairOrder, ProductOrder, ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.IntegerField(default=0, help_text='Base salary')),
                ('overtime_amount', models.IntegerField(default=0, help_text='Overtime')),
                ('bonus', models.IntegerField(default=0, help_text='Bonus')),
                ('housing_allowance', models.IntegerField(default=0, help_text='Housing allowance')),
                ('food_allowance', models.IntegerField(default=0, help_text='Food allowance')),
                ('transportation_allowance', models.IntegerField(default=0, help_text='Transportation allowance')),
                ('insurance_deduction', models.IntegerField(default=0, help_text='Insurance deduction')),
                ('tax_deduction', models.IntegerField(default=0, help_text='Tax deduction')),
                ('loan_deduction', models.IntegerField(default=0, help_text='Loan installment deduction')),
                ('other_deductions', models.IntegerField(default=0, help_text='Other deductions')),
                ('work_days', models.IntegerField(default=0, help_text='Work days')),
                ('overtime_hours', models.IntegerField(default=0, help_text='Overtime hours')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(limit_choices_to={'is_payroll': True}, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_detail', to='accounting.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('direction', models.CharField(choices=[('in', 'دریافت'), ('out', 'پرداخت')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.accountside')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.invoice')),
            ],
        ),
    ]
