# Generated by Django 5.2.3 on 2026-06-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='delivery_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_customer', to='accounting.deliveryman'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='delivery_to_drgame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_console_to_drgame', to='accounting.deliveryman'),
        ),
    ]
