# Generated by Django 5.2.3 on 2026-06-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('crm', '0001_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employee', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='sony_accounts',
            field=models.ManyToManyField(blank=True, to='inventory.sonyaccount'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='account_setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_setter', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='data_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_uploader', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.game'),
        ),
        migrations.AddField(
            model_name='gameorderitem',
            name='game_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='accounting.gameorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='accounting.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='delivery_to_customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_to_customer', to='accounting.deliveryman'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='delivery_to_drgame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_to_drgame', to='accounting.deliveryman'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='repair_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.repairman'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.repairordertype'),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='sony_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sonyaccount'),
        ),
    ]
