# Generated by Django 5.2.3 on 2026-07-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sheba', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'ورودی'), ('out', 'خروجی')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='delivery_to_drgame',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='delivery_to_customer',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='delivery_to_customer',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='delivery_to_drgame',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='sony_accounts',
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='gameorderitem',
            name='game_order',
        ),
        migrations.RemoveField(
            model_name='gameorderitem',
            name='account_setter',
        ),
        migrations.RemoveField(
            model_name='gameorderitem',
            name='data_uploader',
        ),
        migrations.RemoveField(
            model_name='gameorderitem',
            name='game',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='repair_man',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='telegramorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='telegramorder',
            name='sony_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='in_out',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer_str',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_str',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('in', 'دریافت'), ('out', 'پرداخت')], default='in', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AccountSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('customer', 'مشتری'), ('employee', 'کارمند'), ('supplier', 'تامین\u200cکننده'), ('other', 'سایر')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='نوع مدل مرتبط (Customer، Employee، Supplier)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_side',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.accountside'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0, help_text='مجموع مبلغ پرداخت\u200cشده — از Celery آپدیت می\u200cشه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('primary', 'صادر شده'), ('finalize', 'نهایی')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20)),
                ('is_payroll', models.BooleanField(default=False, help_text='آیا این فاکتور فیش حقوقیه؟')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.accountside')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.invoicecategory')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.invoice'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='نوع مدل مرتبط (SonyAccountOrder، RepairOrder، ProductOrder و...)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.IntegerField(default=0, help_text='حقوق پایه')),
                ('overtime_amount', models.IntegerField(default=0, help_text='اضافه\u200cکاری')),
                ('bonus', models.IntegerField(default=0, help_text='پاداش')),
                ('housing_allowance', models.IntegerField(default=0, help_text='حق مسکن')),
                ('food_allowance', models.IntegerField(default=0, help_text='حق خوار و بار')),
                ('transportation_allowance', models.IntegerField(default=0, help_text='حق ایاب و ذهاب')),
                ('insurance_deduction', models.IntegerField(default=0, help_text='کسر بیمه')),
                ('tax_deduction', models.IntegerField(default=0, help_text='کسر مالیات')),
                ('loan_deduction', models.IntegerField(default=0, help_text='کسر اقساط وام')),
                ('other_deductions', models.IntegerField(default=0, help_text='سایر کسورات')),
                ('work_days', models.IntegerField(default=0, help_text='روزهای کارکرد')),
                ('overtime_hours', models.IntegerField(default=0, help_text='ساعات اضافه\u200cکاری')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(limit_choices_to={'is_payroll': True}, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_detail', to='accounting.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseOrder',
        ),
        migrations.DeleteModel(
            name='DeliveryMan',
        ),
        migrations.DeleteModel(
            name='GameOrder',
        ),
        migrations.DeleteModel(
            name='GameOrderItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='RepairOrderType',
        ),
        migrations.DeleteModel(
            name='RepairOrder',
        ),
        migrations.DeleteModel(
            name='TelegramOrder',
        ),
    ]
