# Generated by Django 5.2.3 on 2026-07-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_wallet'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0004_employeerequesttype_remove_repairman_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('charge_admin', 'شارژ توسط ادمین'), ('charge_gateway', 'شارژ آنلاین'), ('debit_order', 'کسر بابت سفارش'), ('refund', 'برگشت وجه')], max_length=20)),
                ('amount', models.PositiveBigIntegerField(help_text='مبلغ به تومان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('gateway_ref', models.CharField(blank=True, help_text='شناسه پرداخت درگاه', max_length=100, null=True)),
                ('gateway_name', models.CharField(blank=True, help_text='مثال: zarinpal', max_length=50, null=True)),
                ('order_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('balance_before', models.PositiveBigIntegerField(help_text='موجودی قبل از تراکنش')),
                ('balance_after', models.PositiveBigIntegerField(help_text='موجودی بعد از تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(blank=True, help_text='فقط برای charge_admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
